# Generated by Django 5.1.6 on 2025-02-24 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movie_combined_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_interaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_interactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='weekly_views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MovieInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('SEARCH', 'Search Query'), ('VIEW', 'Movie View'), ('RECOMMEND', 'Recommendation Click'), ('RATING', 'Rating Given'), ('FAVORITE', 'Added to Favorites'), ('SHARE', 'Shared Movie')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['movie', 'interaction_type', 'timestamp'], name='core_moviei_movie_i_d0ffb2_idx'), models.Index(fields=['timestamp'], name='core_moviei_timesta_ae6345_idx')],
            },
        ),
    ]
