# Generated by Django 5.1.6 on 2025-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_last_interaction_movie_popularity_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('SUCCESS', 'Success')], max_length=10)),
                ('message', models.TextField()),
                ('task_name', models.CharField(max_length=100)),
                ('traceback', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
