# Generated by Django 5.1.6 on 2025-02-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_movieinteraction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('SEARCH', 'Search Query'), ('VIEW', 'Movie View'), ('RECOMMEND', 'Recommendation Click'), ('FAVORITE', 'Added to Favorites'), ('WATCHLIST', 'Added to Watchlist'), ('WATCHED', 'Watched already')], max_length=50),
        ),
    ]
