# Generated by Django 5.1.6 on 2025-02-25 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_movieinteraction_interaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('VIEW', 'Movie View'), ('RECOMMEND', 'Recommendation Click'), ('FAVORITE', 'Added to Favorites'), ('WATCHLIST', 'Added to Watchlist'), ('WATCHED', 'Watched already')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=10)),
                ('favorite_genres', models.JSONField(default=list)),
                ('watch_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('OCCASIONALLY', 'Occasionally'), ('FEW TIMES A MONTH', 'Few times a month'), ('MONTHLY', 'Monthly'), ('FEW TIMES A MONTH', 'Few times a month'), ('YEARLY', 'Yearly')], max_length=50)),
                ('taste', models.CharField(choices=[('AWFUL', 'Awful'), ('MEH', 'Meh'), ('GOOD', 'Good'), ('AMAZING', 'Amazing'), ('HAVENT SEEN', 'Havent seen')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
