# Generated by Django 5.1.6 on 2025-02-26 15:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_movieinteraction_interaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(choices=[('AWFUL', 'Awful'), ('MEH', 'Meh'), ('GOOD', 'Good'), ('AMAZING', 'Amazing'), ('HAVENT SEEN', 'Havent seen')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='taste',
        ),
        migrations.AddField(
            model_name='movie',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='core_movie_title_e933de_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['movie_index'], name='core_movie_movie_i_39c029_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['avg_rating'], name='core_movie_avg_rat_80d101_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity_score'], name='core_movie_popular_3966dc_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-created_at'], name='core_movie_created_e4a52b_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(condition=models.Q(('popularity_score__gt', 0)), fields=['-popularity_score'], name='popular_movies_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='movie_search_vector_idx'),
        ),
        migrations.AddField(
            model_name='movietaste',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
        migrations.AddField(
            model_name='movietaste',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
