# Generated by Django 5.1.6 on 2025-03-02 03:35

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movietaste_remove_userpreference_taste_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mapped_movie_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mapped_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_index',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='mapped_movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='mapped_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0, message='Rating must be at least 1'), django.core.validators.MaxValueValidator(5.0, message='Rating cannot exceed 5')]),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['mapped_user_id'], name='core_rating_mapped__292b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['mapped_movie_id'], name='core_rating_mapped__d2e3f8_idx'),
        ),
    ]
