# Generated by Django 5.1.6 on 2025-03-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userembeddings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmbeddings',
        ),
    ]
