# Generated by Django 5.1.6 on 2025-03-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userembeddings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mapped_user_id',
        ),
    ]
