# Generated by Django 5.1.6 on 2025-03-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_profile_mapped_user_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='core_rating_mapped__292b5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='core_rating_mapped__d2e3f8_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_index',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='mapped_movie_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='mapped_user_id',
        ),
    ]
