# Generated by Django 5.1.1 on 2024-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='hello@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
