# Generated by Django 5.1.1 on 2024-12-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_useraccount_groups_useraccount_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='source',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=100),
        ),
    ]
