# Generated by Django 5.1.6 on 2025-02-10 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_movie_ems_id_alter_movie_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecrew',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='core.movie'),
        ),
    ]
